const fullName: string = 'Duncan Harrison';
const isCool: boolean = false;
const totalPets: number = 1;
const empty: null = null;
let nothing: undefined;
console.log('value of fullName: ', fullName);
console.log('value of isCool: ', isCool);
console.log('value of totalPets: ', totalPets);
console.log('typeof fullName: ', typeof fullName);
console.log('typeof isCool: ', typeof isCool);
console.log('typeof totalPets: ', typeof totalPets);
console.log('value of empty: ', empty);
console.log('typeof empty: ', typeof empty);
console.log('value of nothing: ', nothing);
console.log('typeof nothing: ', typeof nothing);
